language: java
jdk:
  - oraclejdk8
notifications:
  email: true
notifications:
    email:
        recipients:
            - andrew.international@gmail.com
        on_success: change
        on_failure: always
